---
- hosts: bcec_ctl
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: install iptables
    shell: "yum -y install iptables*"
    ignore_errors: yes
    tags: iptables

  - name: stop firewalld service
    shell: "systemctl stop firewalld && systemctl disable firewalld"
    tags: iptables

  - name: copy over the iptables configuration
    template: src=iptables_ctl.conf dest=/etc/sysconfig/iptables
    tags: iptables

  - name: restart iptables
    command: systemctl restart iptables
    tags: iptables
   
- hosts: bcec_cpt
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:

  - name: remove iptable_cpt
    shell: "rm -f iptables_cpt"
    pgnore_errors: yes
    tags: iptables

  - name: install iptables
    shell: "yum -y install iptables*"
    ignore_errors: yes
    tags: iptables

  - name: stop firewalld service
    shell: "systemctl stop firewalld && systemctl disable firewalld"
    tags: iptables

  - name: copy over the iptables configuration
    template: src=iptables_cpt.conf dest=/etc/sysconfig/iptables
    tags: iptables
    
  - name: restart iptables
    command: systemctl restart iptables
    tags: iptables
