---
- hosts: bcec_ha
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: install haproxy
    yum: package=haproxy state=present update_cache=yes
    tags: haproxy

  - name: copy over the haproxy configuration
    template: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg
    notify:
      - restart haproxy
    tags: haproxy

  - name: ensure haproxy is started up
    service: name=haproxy state=started enabled=yes
    tags: haproxy

  handlers:
  - name: restart haproxy
    service: name=haproxy state=restarted
