---
sources:
    - name: meter_source
      interval: 600
      meters:
          - "instance"
          - "instance_flavor"
          - "memory.usage"
          - "memory.resident"
      sinks:
          - meter_sink
    - name: cpu_source
      interval: 6
      meters:
          - "cpu"
      sinks:
          - cpu_sink
    - name: disk_source
      interval: 6
      meters:
          - "disk.read.bytes"
          - "disk.read.requests"
          - "disk.write.bytes"
          - "disk.write.requests"
          - "disk.device.read.bytes"
          - "disk.device.read.requests"
          - "disk.device.write.bytes"
          - "disk.device.write.requests"
      sinks:
          - disk_sink
    - name: network_source
      interval: 6
      meters:
          - "network.incoming.bytes"
          - "network.incoming.packets"
          - "network.outgoing.bytes"
          - "network.outgoing.packets"
      sinks:
          - network_sink
    - name: qemu_source
      interval: 6 
      meters:
          - "disk.usage"
          - "disk.allocation"
          - "disk.capacity"
          - "disk.device.usage"
          - "disk.device.allocation"
          - "disk.device.capacity"
          - "memory.total"
          - "memory.unused"
          - "memory.swap.total"
          - "memory.swap.free"
          - "memory.buffer"
          - "memory.cached"
          - "disk.total"
          - "disk.free"
          - "disk.percent"
          - "disk.latency"
          - "disk.device.latency"
          - "disk.iops"
          - "disk.device.iops"
      sinks:
          - meter_sink
sinks:
    - name: meter_sink
      transformers:
      publishers:
          - udp://{{ groups['bcec_ceilometer_collector'][0] }}
          - udp://{{ groups['bcec_ceilometer_clm_vip'][0] }}
    - name: cpu_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                target:
                    name: "cpu_util"
                    unit: "%"
                    type: "gauge"
                    scale: "100.0 / (10**9 * (resource_metadata.cpu_number or 1))"
      publishers:
          - udp://{{ groups['bcec_ceilometer_collector'][0] }}
          - udp://{{ groups['bcec_ceilometer_clm_vip'][0] }}
    - name: disk_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                source:
                    map_from:
                        name: "(disk\\.device|disk)\\.(read|write)\\.(bytes|requests)"
                        unit: "(B|request)"
                target:
                    map_to:
                        name: "\\1.\\2.\\3.rate"
                        unit: "KB/s"
                    type: "gauge"
                    scale: "volume * 1.0 / 1024.0"
      publishers:
          - udp://{{ groups['bcec_ceilometer_collector'][0] }}
          - udp://{{ groups['bcec_ceilometer_clm_vip'][0] }}
    - name: network_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                source:
                   map_from:
                       name: "network\\.(incoming|outgoing)\\.(bytes|packets)"
                       unit: "(B|packet)"
                target:
                    map_to:
                        name: "network.\\1.\\2.rate"
                        unit: "\\1/s"
                    type: "gauge"
      publishers:
          - udp://{{ groups['bcec_ceilometer_collector'][0] }}
          - udp://{{ groups['bcec_ceilometer_clm_vip'][0] }}

