---
- hosts: bcec_cpt
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: install nova-compute
    yum: name=openstack-nova-compute state=present update_cache=yes
    tags: nova

  - name: install sysfsutils
    yum: name=sysfsutils state=present update_cache=yes
    tags: nova

  - name: copy over the ntp configuration
    template: src=nova-cpt.conf dest=/etc/nova/nova.conf
    notify:
          - enable nova
          - restart nova
    tags: nova

  - name: ensure nova is started up
    service: name=openstack-nova-compute state=started enabled=yes
    tags: nova

  handlers:
  - name: enable nova
    shell: "systemctl enable libvirtd.service openstack-nova-compute.service"

  - name: restart nova
    shell: "systemctl start libvirtd.service openstack-nova-compute.service"
